version: '3'
services:
  mongo:
    image: mongo
    container_name: rmongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - /data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: rmongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  api:
    build: docker/api
    container_name: recipeapi
    restart: always
    ports: 
      - 3001:3001
    volumes: 
      - ./:/usr/src/app